import { ModelType } from '../base';

export const PoePointsMap: Partial<Record<ModelType, number>> = {
  [ModelType.Assistant]: 20,
  [ModelType.StableDiffusion]: 80,
  [ModelType.MistralMedium]: 165,
  [ModelType.Qwen72bChat]: 15,
  [ModelType.GeminiPro]: 40,
  [ModelType.PlaygroundV2]: 40,
  [ModelType.GPT4]: 350,
  [ModelType.Claude2]: 750,
  [ModelType.DallE3]: 1500,
  [ModelType.GPT3p5Turbo]: 20,
  [ModelType.GPT3p5_16k]: 120,
  [ModelType.Fw_mistral_7b]: 5,
  [ModelType.GPT3p5TurboInstruct]: 20,
  [ModelType.Llama_2_70b]: 50,
  [ModelType.Llama_2_13b]: 15,
  [ModelType.Llama_2_7b]: 5,
  [ModelType.ClaudeInstant]: 30,
  [ModelType.GooglePalm]: 50,
  [ModelType.ClaudeInstant_100k]: 75,
  [ModelType.GPT4_32k]: 2500,
  [ModelType.Mixtral8x7BChat]: 20,
  [ModelType.Code_Llama_34b]: 20,
  [ModelType.Code_Llama_13b]: 20,
  [ModelType.Code_Llama_7b]: 15,
  [ModelType.Solar_0_70b]: 1,
  [ModelType.Claude3Sonnet]: 150,
  [ModelType.Claude3Sonnet200k]: 375,
  [ModelType.Claude3Opus]: 750,
  [ModelType.Claude3Opus200k]: 1875,
  [ModelType.Gemma7bFW]: 5,
  [ModelType.Claude3Haiku]: 30,
  [ModelType.Claude3Sonnet200k]: 200,
};

export const PoeModelMap: Partial<Record<ModelType, any>> = {
  [ModelType.Sage]: 'Assistant',
  [ModelType.StableDiffusion]: 'StableDiffusionXL',
  [ModelType.MistralMedium]: 'Mistral-Medium',
  [ModelType.Qwen72bChat]: 'Qwen-72b-Chat',
  [ModelType.GeminiPro]: 'Gemini-Pro',
  [ModelType.GPT4]: 'GPT-4',
  [ModelType.GPT3p5_16k]: 'ChatGPT-16k',
  [ModelType.GPT4_32k]: 'GPT-4-32k',
  [ModelType.GPT3p5Turbo]: 'ChatGPT',
  [ModelType.ClaudeInstant_100k]: 'Claude-instant-100k',
  [ModelType.ClaudeInstant]: 'Claude-instant',
  [ModelType.GooglePalm]: 'Google-PaLM',
  [ModelType.Claude2]: 'Claude-2-100k',
  [ModelType.Llama_2_70b]: 'Llama-2-70b',
  [ModelType.Llama_2_13b]: 'Llama-2-13b',
  [ModelType.Llama_2_7b]: 'Llama-2-7b',
  [ModelType.Code_Llama_34b]: 'Code-Llama-34b',
  [ModelType.Code_Llama_13b]: 'Code-Llama-13b',
  [ModelType.Code_Llama_7b]: 'Code-Llama-7b',
  [ModelType.GPT3p5TurboInstruct]: 'GPT-3.5-Turbo-Instruct',
  [ModelType.Solar_0_70b]: 'Solar-0-70b',
  [ModelType.Fw_mistral_7b]: 'fw-mistral-7b',
  [ModelType.DallE3]: 'DALL-E-3',
  [ModelType.PlaygroundV2]: 'Playground-v2',
  [ModelType.GeminiProVision]: 'Gemini-Pro',
  [ModelType.Mixtral8x7BChat]: 'Mixtral-8x7B-Chat',
  [ModelType.Claude3Opus]: 'Claude-3-Opus',
  [ModelType.Claude3Opus200k]: 'Claude-3-Opus-200k',
  [ModelType.Claude3Sonnet]: 'Claude-3-Sonnet',
  [ModelType.Claude3Sonnet200k]: 'Claude-3-Sonnet-200k',
  [ModelType.Claude3Haiku]: 'Claude-3-Haiku',
  [ModelType.Claude3Haiku200k]: 'Claude-3-Haiku-200k',
  [ModelType.Gemma7bFW]: 'Gemma-7b-FW',
};
